Get rails 3.2.21 and ruby 2.4 passing
For some reason this combo results in TypeError:

```
Failures:
  1) Flipper::Adapters::ActiveRecord it should behave like a flipper
adapter can add, remove and list known features
     Failure/Error: unless @feature_class.where(key: feature.key).first

     TypeError:
       Cannot visit Integer
     Shared Example Group: "a flipper adapter" called from
./spec/flipper/adapters/active_record_spec.rb:47
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:25:in
`rescue in visit'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in
`visit'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:241:in
`visit_Arel_Nodes_Limit'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in
`visit'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:123:in
`visit_Arel_Nodes_SelectStatement'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/sqlite.rb:12:in
`visit_Arel_Nodes_SelectStatement'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in
`visit'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:5:in
`accept'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/to_sql.rb:19:in
`accept'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:7:in
`to_sql'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in
`select_all'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in
`select_all'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/querying.rb:38:in
`block in find_by_sql'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/explain.rb:26:in
`logging_query_plan'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/querying.rb:37:in
`find_by_sql'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/relation.rb:171:in
`exec_queries'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/relation.rb:160:in
`block in to_a'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/explain.rb:26:in
`logging_query_plan'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/relation.rb:159:in
`to_a'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/relation/finder_methods.rb:381:in
`find_first'
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/activerecord-3.2.22.5/lib/active_record/relation/finder_methods.rb:122:in
`first'
     # ./lib/flipper/adapters/active_record.rb:50:in `add'
     # ./lib/flipper/spec/shared_adapter_specs.rb:186:in `block (2
levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `visit_Integer' for
#<Arel::Visitors::SQLite:0x00000004d86540>
     #   Did you mean?  visit_String
     #
/home/travis/.rvm/gems/ruby-2.4.1/gems/arel-3.0.3/lib/arel/visitors/visitor.rb:19:in
`visit'
```

This fixes it. Stupid, but should be fine because there will only ever
be one feature with a given key thanks to the unique index.